#' Return a skeleton of a ggplot2 plot of solar system plot
#'
#' THIS JUST A LAZY HELPER FUNCTION UNTIL I HAVE TIME TO WRITE GEOMS
#'
#' If you need to be able to vary planet size/color/fill/etc by the
#' planet name, or you want different orbit aesthetics mapped by planet,
#' you'll need, for now, to run [scaffold_planet_plot()] which will place
#' a textual copy of this function to stdout that you can copy and
#' use at-will.
#'
#' Given a data frame built with [generate_orbits()] and another
#' data frame of planet positions, theoretically generated by
#' [randomize_planet_positions()], return a ggplot2 skeleton with —
#' at a minimum — a polygon geom and point geom. A text geom can
#' optionally be added, but only naive positioning of labels is performed.
#'
#' \if{html}{
#'   \out{<div style="text-align: center">}\figure{README-sol-1.png}{options: style="width:750px;max-width:75\%;"}\out{</div>}
#' }
#'
#' \if{latex}{
#'   \out{\begin{center}}\figure{README-sol-1.png}\out{\end{center}}
#' }
#'
#' @param orbits (df)
#' @param planet_positions (df)
#' @param label_planets (bool) if `TRUE`, then planet labels will be
#'        naively placed to the right of each planet point.
#' @param orbit_fill,orbit_color,orbit_linewidth defaults
#' @param planet_size,planet_shape,planet_stroke,planet_color,planet_fill defaults
#' @param label_color,label_size,label_family,label_hjust defaults (if `label_planets` is `TRUE`)
#' @return ggplot2 object
#' @export
#' @examples
#' library(ggplot2)
#'
#' sol_orbits <- generate_orbits(sol_planets)
#'
#' set.seed(1323)
#'
#' placed_planets <- randomize_planet_positions(sol_orbits)
#'
#' plot_orbits(
#'   orbits = sol_orbits,
#'   planet_positions = placed_planets,
#'   label_planets = TRUE,
#' ) +
#'   ggplot2::theme_void() +
#'   ggplot2::coord_equal() +
#'   ggplot2::labs(
#'     title = "Sol",
#'     caption = "Pluto is 100% a planet"
#'   ) +
#'   theme_enhance_solar()
plot_orbits <- function (orbits,
                         planet_positions,
                         label_planets = FALSE,
                         orbit_fill = NA,
                         orbit_color = "white",
                         orbit_linewidth = 0.125/2,
                         planet_size = 3,
                         planet_shape = 21,
                         planet_stroke = 0.5,
                         planet_color = "#fea100",
                         planet_fill = ggplot2::alpha("#fea100", 1/4),
                         label_color = "white",
                         label_size = 3,
                         label_family = "sans",
                         label_hjust = 0
) {

  gg <- ggplot2::ggplot()

  gg + geom_circle(
    data = orbits,
    aes(
      x0 = 0,
      y0 = 0,
      r = radius
    ),
    color = orbit_color,
    fill = orbit_fill,
    color = alpha("white", 1/2),
    size = orbit_linewidth,
  ) -> gg

  gg + ggplot2::geom_point(
    data = planet_positions,
    ggplot2::aes(x, y, group=planet),
    color = planet_color,
    fill = planet_fill,
    size = planet_size,
    shape = planet_shape,
    stroke = planet_stroke
  ) -> gg


  if (label_planets) {
    gg +  ggplot2::geom_text(
      data = planet_positions,
      ggplot2::aes(x, y, group=planet, label = sprintf("    %s", planet)),
      color = label_color,
      size = label_size,
      family = label_family,
      hjust = label_hjust
    ) -> gg
  }

  gg

}


#' Get a boilerplate to work from
#'
#' @export
scaffold_planet_plot <- function() {

  cat(
    '# Use your own data/seed!!
sol_dist <- sqrt(c(0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.18, 30.07, 39.48))
sol_orbits <- generate_orbits(sol_planets, radii = sol_dist, num_polygon_points = 1000)

set.seed(42)
sol_placements <- randomize_planet_positions(sol_orbits)

ggplot() +
  geom_circle(
    data = sol_orbits,
    aes(
      x0 = 0,
      y0 = 0,
      r = radius
    ),
    color = alpha("white", 1/2),
    size = 0.125
  ) +
  geom_point(
    data = sol_placements,
    aes(x, y),
    color = "orange",
    fill = alpha("orange", 1/2),
    size = 3,
    shape = 21,
    stroke = 1
  ) +
  coord_fixed() +
  theme_void(grid="") +
  theme_enhance_solar()
')

}
